var countries=[
{"cont_code":"AS","continent":"Asia","country_code":"AF","country_code3":"AFG","country_no":"4","country":"Afghanistan"},
{"cont_code":"EU","continent":"Europe","country_code":"AX","country_code3":"ALA","country_no":"248","country":"Aland Islands"},
{"cont_code":"EU","continent":"Europe","country_code":"AL","country_code3":"ALB","country_no":"8","country":"Albania"},
{"cont_code":"AF","continent":"Africa","country_code":"DZ","country_code3":"DZA","country_no":"12","country":"Algeria"},
{"cont_code":"OC","continent":"Oceania","country_code":"AS","country_code3":"ASM","country_no":"16","country":"American Samoa"},
{"cont_code":"EU","continent":"Europe","country_code":"AD","country_code3":"AND","country_no":"20","country":"Andorra"},
{"cont_code":"AF","continent":"Africa","country_code":"AO","country_code3":"AGO","country_no":"24","country":"Angola"},
{"cont_code":"NA","continent":"North America","country_code":"AI","country_code3":"AIA","country_no":"660","country":"Anguilla"},
{"cont_code":"AN","continent":"Antarctica","country_code":"AQ","country_code3":"ATA","country_no":"10","country":"Antarctica"},
{"cont_code":"NA","continent":"North America","country_code":"AG","country_code3":"ATG","country_no":"28","country":"Antigua and Barbuda"},
{"cont_code":"SA","continent":"South America","country_code":"AR","country_code3":"ARG","country_no":"32","country":"Argentina"},
{"cont_code":"AS","continent":"Asia","country_code":"AM","country_code3":"ARM","country_no":"51","country":"Armenia"},
{"cont_code":"NA","continent":"North America","country_code":"AW","country_code3":"ABW","country_no":"533","country":"Aruba"},
{"cont_code":"OC","continent":"Oceania","country_code":"AU","country_code3":"AUS","country_no":"36","country":"Australia"},
{"cont_code":"EU","continent":"Europe","country_code":"AT","country_code3":"AUT","country_no":"40","country":"Austria"},
{"cont_code":"AS","continent":"Asia","country_code":"AZ","country_code3":"AZE","country_no":"31","country":"Azerbaijan"},
{"cont_code":"NA","continent":"North America","country_code":"BS","country_code3":"BHS","country_no":"44","country":"Bahamas"},
{"cont_code":"AS","continent":"Asia","country_code":"BH","country_code3":"BHR","country_no":"48","country":"Bahrain"},
{"cont_code":"AS","continent":"Asia","country_code":"BD","country_code3":"BGD","country_no":"50","country":"Bangladesh"},
{"cont_code":"NA","continent":"North America","country_code":"BB","country_code3":"BRB","country_no":"52","country":"Barbados"},
{"cont_code":"EU","continent":"Europe","country_code":"BY","country_code3":"BLR","country_no":"112","country":"Belarus"},
{"cont_code":"EU","continent":"Europe","country_code":"BE","country_code3":"BEL","country_no":"56","country":"Belgium"},
{"cont_code":"NA","continent":"North America","country_code":"BZ","country_code3":"BLZ","country_no":"84","country":"Belize"},
{"cont_code":"AF","continent":"Africa","country_code":"BJ","country_code3":"BEN","country_no":"204","country":"Benin"},
{"cont_code":"NA","continent":"North America","country_code":"BM","country_code3":"BMU","country_no":"60","country":"Bermuda"},
{"cont_code":"AS","continent":"Asia","country_code":"BT","country_code3":"BTN","country_no":"64","country":"Bhutan"},
{"cont_code":"SA","continent":"South America","country_code":"BO","country_code3":"BOL","country_no":"68","country":"Bolivia"},
{"cont_code":"EU","continent":"Europe","country_code":"BA","country_code3":"BIH","country_no":"70","country":"Bosnia and Herzegovina"},
{"cont_code":"AF","continent":"Africa","country_code":"BW","country_code3":"BWA","country_no":"72","country":"Botswana"},
{"cont_code":"AN","continent":"Antarctica","country_code":"BV","country_code3":"BVT","country_no":"74","country":"Bouvet Island"},
{"cont_code":"SA","continent":"South America","country_code":"BR","country_code3":"BRA","country_no":"76","country":"Brazil"},
{"cont_code":"AS","continent":"Asia","country_code":"IO","country_code3":"IOT","country_no":"86","country":"British Indian Ocean Territory"},
{"cont_code":"NA","continent":"North America","country_code":"VG","country_code3":"VGB","country_no":"92","country":"British Virgin Islands"},
{"cont_code":"AS","continent":"Asia","country_code":"BN","country_code3":"BRN","country_no":"96","country":"Brunei Darussalam"},
{"cont_code":"EU","continent":"Europe","country_code":"BG","country_code3":"BGR","country_no":"100","country":"Bulgaria"},
{"cont_code":"AF","continent":"Africa","country_code":"BF","country_code3":"BFA","country_no":"854","country":"Burkina Faso"},
{"cont_code":"AF","continent":"Africa","country_code":"BI","country_code3":"BDI","country_no":"108","country":"Burundi"},
{"cont_code":"AS","continent":"Asia","country_code":"KH","country_code3":"KHM","country_no":"116","country":"Cambodia"},
{"cont_code":"AF","continent":"Africa","country_code":"CM","country_code3":"CMR","country_no":"120","country":"Cameroon"},
{"cont_code":"NA","continent":"North America","country_code":"CA","country_code3":"CAN","country_no":"124","country":"Canada"},
{"cont_code":"AF","continent":"Africa","country_code":"CV","country_code3":"CPV","country_no":"132","country":"Cape Verde"},
{"cont_code":"NA","continent":"North America","country_code":"KY","country_code3":"CYM","country_no":"136","country":"Cayman Islands"},
{"cont_code":"AF","continent":"Africa","country_code":"CF","country_code3":"CAF","country_no":"140","country":"Central African Republic"},
{"cont_code":"AF","continent":"Africa","country_code":"TD","country_code3":"TCD","country_no":"148","country":"Chad"},
{"cont_code":"SA","continent":"South America","country_code":"CL","country_code3":"CHL","country_no":"152","country":"Chile"},
{"cont_code":"AS","continent":"Asia","country_code":"CN","country_code3":"CHN","country_no":"156","country":"China"},
{"cont_code":"AS","continent":"Asia","country_code":"CX","country_code3":"CXR","country_no":"162","country":"Christmas Island"},
{"cont_code":"AS","continent":"Asia","country_code":"CC","country_code3":"CCK","country_no":"166","country":"Cocos Islands"},
{"cont_code":"SA","continent":"South America","country_code":"CO","country_code3":"COL","country_no":"170","country":"Colombia"},
{"cont_code":"AF","continent":"Africa","country_code":"KM","country_code3":"COM","country_no":"174","country":"Comoros"},
{"cont_code":"AF","continent":"Africa","country_code":"CD","country_code3":"COD","country_no":"180","country":"Congo (DR)"},
{"cont_code":"AF","continent":"Africa","country_code":"CG","country_code3":"COG","country_no":"178","country":"Congo (PR)"},
{"cont_code":"OC","continent":"Oceania","country_code":"CK","country_code3":"COK","country_no":"184","country":"Cook Islands"},
{"cont_code":"NA","continent":"North America","country_code":"CR","country_code3":"CRI","country_no":"188","country":"Costa Rica"},
{"cont_code":"AF","continent":"Africa","country_code":"CI","country_code3":"CIV","country_no":"384","country":"Cote D'Ivoire"},
{"cont_code":"EU","continent":"Europe","country_code":"HR","country_code3":"HRV","country_no":"191","country":"Croatia"},
{"cont_code":"NA","continent":"North America","country_code":"CU","country_code3":"CUB","country_no":"192","country":"Cuba"},
{"cont_code":"AS","continent":"Asia","country_code":"CY","country_code3":"CYP","country_no":"196","country":"Cyprus"},
{"cont_code":"EU","continent":"Europe","country_code":"CZ","country_code3":"CZE","country_no":"203","country":"Czech Republic"},
{"cont_code":"EU","continent":"Europe","country_code":"DK","country_code3":"DNK","country_no":"208","country":"Denmark"},
{"cont_code":"AF","continent":"Africa","country_code":"DJ","country_code3":"DJI","country_no":"262","country":"Djibouti"},
{"cont_code":"NA","continent":"North America","country_code":"DM","country_code3":"DMA","country_no":"212","country":"Dominica"},
{"cont_code":"NA","continent":"North America","country_code":"DO","country_code3":"DOM","country_no":"214","country":"Dominican Republic"},
{"cont_code":"SA","continent":"South America","country_code":"EC","country_code3":"ECU","country_no":"218","country":"Ecuador"},
{"cont_code":"AF","continent":"Africa","country_code":"EG","country_code3":"EGY","country_no":"818","country":"Egypt"},
{"cont_code":"NA","continent":"North America","country_code":"SV","country_code3":"SLV","country_no":"222","country":"El Salvador"},
{"cont_code":"AF","continent":"Africa","country_code":"GQ","country_code3":"GNQ","country_no":"226","country":"Equatorial Guinea"},
{"cont_code":"AF","continent":"Africa","country_code":"ER","country_code3":"ERI","country_no":"232","country":"Eritrea"},
{"cont_code":"EU","continent":"Europe","country_code":"EE","country_code3":"EST","country_no":"233","country":"Estonia"},
{"cont_code":"AF","continent":"Africa","country_code":"ET","country_code3":"ETH","country_no":"231","country":"Ethiopia"},
{"cont_code":"EU","continent":"Europe","country_code":"FO","country_code3":"FRO","country_no":"234","country":"Faroe Islands"},
{"cont_code":"SA","continent":"South America","country_code":"FK","country_code3":"FLK","country_no":"238","country":"Falkland Islands"},
{"cont_code":"OC","continent":"Oceania","country_code":"FJ","country_code3":"FJI","country_no":"242","country":"Fiji"},
{"cont_code":"EU","continent":"Europe","country_code":"FI","country_code3":"FIN","country_no":"246","country":"Finland"},
{"cont_code":"EU","continent":"Europe","country_code":"FR","country_code3":"FRA","country_no":"250","country":"France"},
{"cont_code":"SA","continent":"South America","country_code":"GF","country_code3":"GUF","country_no":"254","country":"French Guiana"},
{"cont_code":"OC","continent":"Oceania","country_code":"PF","country_code3":"PYF","country_no":"258","country":"French Polynesia"},
{"cont_code":"AN","continent":"Antarctica","country_code":"TF","country_code3":"ATF","country_no":"260","country":"French Southern Territories"},
{"cont_code":"AF","continent":"Africa","country_code":"GA","country_code3":"GAB","country_no":"266","country":"Gabon"},
{"cont_code":"AF","continent":"Africa","country_code":"GM","country_code3":"GMB","country_no":"270","country":"Gambia"},
{"cont_code":"AS","continent":"Asia","country_code":"GE","country_code3":"GEO","country_no":"268","country":"Georgia"},
{"cont_code":"EU","continent":"Europe","country_code":"DE","country_code3":"DEU","country_no":"276","country":"Germany"},
{"cont_code":"AF","continent":"Africa","country_code":"GH","country_code3":"GHA","country_no":"288","country":"Ghana"},
{"cont_code":"EU","continent":"Europe","country_code":"GI","country_code3":"GIB","country_no":"292","country":"Gibraltar"},
{"cont_code":"EU","continent":"Europe","country_code":"GR","country_code3":"GRC","country_no":"300","country":"Greece"},
{"cont_code":"NA","continent":"North America","country_code":"GL","country_code3":"GRL","country_no":"304","country":"Greenland"},
{"cont_code":"NA","continent":"North America","country_code":"GD","country_code3":"GRD","country_no":"308","country":"Grenada"},
{"cont_code":"NA","continent":"North America","country_code":"GP","country_code3":"GLP","country_no":"312","country":"Guadaloupe"},
{"cont_code":"OC","continent":"Oceania","country_code":"GU","country_code3":"GUM","country_no":"316","country":"Guam"},
{"cont_code":"NA","continent":"North America","country_code":"GT","country_code3":"GTM","country_no":"320","country":"Guatemala"},
{"cont_code":"EU","continent":"Europe","country_code":"GG","country_code3":"GGY","country_no":"831","country":"Guernsey"},
{"cont_code":"AF","continent":"Africa","country_code":"GN","country_code3":"GIN","country_no":"324","country":"Guinea"},
{"cont_code":"AF","continent":"Africa","country_code":"GW","country_code3":"GNB","country_no":"624","country":"Guinea-Bissau"},
{"cont_code":"SA","continent":"South America","country_code":"GY","country_code3":"GUY","country_no":"328","country":"Guyana"},
{"cont_code":"NA","continent":"North America","country_code":"HT","country_code3":"HTI","country_no":"332","country":"Haiti"},
{"cont_code":"AN","continent":"Antarctica","country_code":"HM","country_code3":"HMD","country_no":"334","country":"Heard and McDonald Islands"},
{"cont_code":"EU","continent":"Europe","country_code":"VA","country_code3":"VAT","country_no":"336","country":"Holy See"},
{"cont_code":"NA","continent":"North America","country_code":"HN","country_code3":"HND","country_no":"340","country":"Honduras"},
{"cont_code":"AS","continent":"Asia","country_code":"HK","country_code3":"HKG","country_no":"344","country":"Hong Kong"},
{"cont_code":"EU","continent":"Europe","country_code":"HU","country_code3":"HUN","country_no":"348","country":"Hungary"},
{"cont_code":"EU","continent":"Europe","country_code":"IS","country_code3":"ISL","country_no":"352","country":"Iceland"},
{"cont_code":"AS","continent":"Asia","country_code":"IN","country_code3":"IND","country_no":"356","country":"India"},
{"cont_code":"AS","continent":"Asia","country_code":"ID","country_code3":"IDN","country_no":"360","country":"Indonesia"},
{"cont_code":"AS","continent":"Asia","country_code":"IR","country_code3":"IRN","country_no":"364","country":"Iran"},
{"cont_code":"AS","continent":"Asia","country_code":"IQ","country_code3":"IRQ","country_no":"368","country":"Iraq"},
{"cont_code":"EU","continent":"Europe","country_code":"IE","country_code3":"IRL","country_no":"372","country":"Ireland"},
{"cont_code":"EU","continent":"Europe","country_code":"IM","country_code3":"IMN","country_no":"833","country":"Isle of Man"},
{"cont_code":"AS","continent":"Asia","country_code":"IL","country_code3":"ISR","country_no":"376","country":"Israel"},
{"cont_code":"EU","continent":"Europe","country_code":"IT","country_code3":"ITA","country_no":"380","country":"Italy"},
{"cont_code":"NA","continent":"North America","country_code":"JM","country_code3":"JAM","country_no":"388","country":"Jamaica"},
{"cont_code":"AS","continent":"Asia","country_code":"JP","country_code3":"JPN","country_no":"392","country":"Japan"},
{"cont_code":"EU","continent":"Europe","country_code":"JE","country_code3":"JEY","country_no":"832","country":"Jersey"},
{"cont_code":"AS","continent":"Asia","country_code":"JO","country_code3":"JOR","country_no":"400","country":"Jordan"},
{"cont_code":"AS","continent":"Asia","country_code":"KZ","country_code3":"KAZ","country_no":"398","country":"Kazakhstan"},
{"cont_code":"AF","continent":"Africa","country_code":"KE","country_code3":"KEN","country_no":"404","country":"Kenya"},
{"cont_code":"OC","continent":"Oceania","country_code":"KI","country_code3":"KIR","country_no":"296","country":"Kiribati"},
{"cont_code":"AS","continent":"Asia","country_code":"KP","country_code3":"PRK","country_no":"408","country":"Korea (DPR)"},
{"cont_code":"AS","continent":"Asia","country_code":"KR","country_code3":"KOR","country_no":"410","country":"Korea"},
{"cont_code":"AS","continent":"Asia","country_code":"KW","country_code3":"KWT","country_no":"414","country":"Kuwait"},
{"cont_code":"AS","continent":"Asia","country_code":"KG","country_code3":"KGZ","country_no":"417","country":"Kyrgyzstan"},
{"cont_code":"AS","continent":"Asia","country_code":"LA","country_code3":"LAO","country_no":"418","country":"Lao"},
{"cont_code":"EU","continent":"Europe","country_code":"LV","country_code3":"LVA","country_no":"428","country":"Latvia"},
{"cont_code":"AS","continent":"Asia","country_code":"LB","country_code3":"LBN","country_no":"422","country":"Lebanon"},
{"cont_code":"AF","continent":"Africa","country_code":"LS","country_code3":"LSO","country_no":"426","country":"Lesotho"},
{"cont_code":"AF","continent":"Africa","country_code":"LR","country_code3":"LBR","country_no":"430","country":"Liberia"},
{"cont_code":"AF","continent":"Africa","country_code":"LY","country_code3":"LBY","country_no":"434","country":"Libya"},
{"cont_code":"EU","continent":"Europe","country_code":"LI","country_code3":"LIE","country_no":"438","country":"Liechtenstein"},
{"cont_code":"EU","continent":"Europe","country_code":"LT","country_code3":"LTU","country_no":"440","country":"Lithuania"},
{"cont_code":"EU","continent":"Europe","country_code":"LU","country_code3":"LUX","country_no":"442","country":"Luxembourg"},
{"cont_code":"AS","continent":"Asia","country_code":"MO","country_code3":"MAC","country_no":"446","country":"Macao"},
{"cont_code":"EU","continent":"Europe","country_code":"MK","country_code3":"MKD","country_no":"807","country":"Macedonia"},
{"cont_code":"AF","continent":"Africa","country_code":"MG","country_code3":"MDG","country_no":"450","country":"Madagascar"},
{"cont_code":"AF","continent":"Africa","country_code":"MW","country_code3":"MWI","country_no":"454","country":"Malawi"},
{"cont_code":"AS","continent":"Asia","country_code":"MY","country_code3":"MYS","country_no":"458","country":"Malaysia"},
{"cont_code":"AS","continent":"Asia","country_code":"MV","country_code3":"MDV","country_no":"462","country":"Maldives"},
{"cont_code":"AF","continent":"Africa","country_code":"ML","country_code3":"MLI","country_no":"466","country":"Mali"},
{"cont_code":"EU","continent":"Europe","country_code":"MT","country_code3":"MLT","country_no":"470","country":"Malta"},
{"cont_code":"OC","continent":"Oceania","country_code":"MH","country_code3":"MHL","country_no":"584","country":"Marshall Islands"},
{"cont_code":"NA","continent":"North America","country_code":"MQ","country_code3":"MTQ","country_no":"474","country":"Martinique"},
{"cont_code":"AF","continent":"Africa","country_code":"MR","country_code3":"MRT","country_no":"478","country":"Mauritania"},
{"cont_code":"AF","continent":"Africa","country_code":"MU","country_code3":"MUS","country_no":"480","country":"Mauritius"},
{"cont_code":"AF","continent":"Africa","country_code":"YT","country_code3":"MYT","country_no":"175","country":"Mayotte"},
{"cont_code":"NA","continent":"North America","country_code":"MX","country_code3":"MEX","country_no":"484","country":"Mexico"},
{"cont_code":"OC","continent":"Oceania","country_code":"FM","country_code3":"FSM","country_no":"583","country":"Micronesia"},
{"cont_code":"EU","continent":"Europe","country_code":"MD","country_code3":"MDA","country_no":"498","country":"Moldova"},
{"cont_code":"EU","continent":"Europe","country_code":"MC","country_code3":"MCO","country_no":"492","country":"Monaco"},
{"cont_code":"AS","continent":"Asia","country_code":"MN","country_code3":"MNG","country_no":"496","country":"Mongolia"},
{"cont_code":"EU","continent":"Europe","country_code":"ME","country_code3":"MNE","country_no":"499","country":"Montenegro"},
{"cont_code":"NA","continent":"North America","country_code":"MS","country_code3":"MSR","country_no":"500","country":"Montserrat"},
{"cont_code":"AF","continent":"Africa","country_code":"MA","country_code3":"MAR","country_no":"504","country":"Morocco"},
{"cont_code":"AF","continent":"Africa","country_code":"MZ","country_code3":"MOZ","country_no":"508","country":"Mozambique"},
{"cont_code":"AS","continent":"Asia","country_code":"MM","country_code3":"MMR","country_no":"104","country":"Myanmar"},
{"cont_code":"AF","continent":"Africa","country_code":"NA","country_code3":"NAM","country_no":"516","country":"Namibia"},
{"cont_code":"OC","continent":"Oceania","country_code":"NR","country_code3":"NRU","country_no":"520","country":"Nauru"},
{"cont_code":"AS","continent":"Asia","country_code":"NP","country_code3":"NPL","country_no":"524","country":"Nepal"},
{"cont_code":"NA","continent":"North America","country_code":"AN","country_code3":"ANT","country_no":"530","country":"Netherlands Antilles"},
{"cont_code":"EU","continent":"Europe","country_code":"NL","country_code3":"NLD","country_no":"528","country":"Netherlands"},
{"cont_code":"OC","continent":"Oceania","country_code":"NC","country_code3":"NCL","country_no":"540","country":"New Caledonia"},
{"cont_code":"OC","continent":"Oceania","country_code":"NZ","country_code3":"NZL","country_no":"554","country":"New Zealand"},
{"cont_code":"NA","continent":"North America","country_code":"NI","country_code3":"NIC","country_no":"558","country":"Nicaragua"},
{"cont_code":"AF","continent":"Africa","country_code":"NE","country_code3":"NER","country_no":"562","country":"Niger"},
{"cont_code":"AF","continent":"Africa","country_code":"NG","country_code3":"NGA","country_no":"566","country":"Nigeria"},
{"cont_code":"OC","continent":"Oceania","country_code":"NU","country_code3":"NIU","country_no":"570","country":"Niue"},
{"cont_code":"OC","continent":"Oceania","country_code":"NF","country_code3":"NFK","country_no":"574","country":"Norfolk Island"},
{"cont_code":"OC","continent":"Oceania","country_code":"MP","country_code3":"MNP","country_no":"580","country":"Northern Mariana Islands"},
{"cont_code":"EU","continent":"Europe","country_code":"NO","country_code3":"NOR","country_no":"578","country":"Norway"},
{"cont_code":"AS","continent":"Asia","country_code":"OM","country_code3":"OMN","country_no":"512","country":"Oman"},
{"cont_code":"AS","continent":"Asia","country_code":"PK","country_code3":"PAK","country_no":"586","country":"Pakistan"},
{"cont_code":"OC","continent":"Oceania","country_code":"PW","country_code3":"PLW","country_no":"585","country":"Palau"},
{"cont_code":"AS","continent":"Asia","country_code":"PS","country_code3":"PSE","country_no":"275","country":"Palestinian Territory"},
{"cont_code":"NA","continent":"North America","country_code":"PA","country_code3":"PAN","country_no":"591","country":"Panama"},
{"cont_code":"OC","continent":"Oceania","country_code":"PG","country_code3":"PNG","country_no":"598","country":"Papua New Guinea"},
{"cont_code":"SA","continent":"South America","country_code":"PY","country_code3":"PRY","country_no":"600","country":"Paraguay"},
{"cont_code":"SA","continent":"South America","country_code":"PE","country_code3":"PER","country_no":"604","country":"Peru"},
{"cont_code":"AS","continent":"Asia","country_code":"PH","country_code3":"PHL","country_no":"608","country":"Philippines"},
{"cont_code":"OC","continent":"Oceania","country_code":"PN","country_code3":"PCN","country_no":"612","country":"Pitcairn Island"},
{"cont_code":"EU","continent":"Europe","country_code":"PL","country_code3":"POL","country_no":"616","country":"Poland"},
{"cont_code":"EU","continent":"Europe","country_code":"PT","country_code3":"PRT","country_no":"620","country":"Portugal"},
{"cont_code":"NA","continent":"North America","country_code":"PR","country_code3":"PRI","country_no":"630","country":"Puerto Rico"},
{"cont_code":"AS","continent":"Asia","country_code":"QA","country_code3":"QAT","country_no":"634","country":"Qatar"},
{"cont_code":"AF","continent":"Africa","country_code":"RE","country_code3":"REU","country_no":"638","country":"Reunion"},
{"cont_code":"EU","continent":"Europe","country_code":"RO","country_code3":"ROU","country_no":"642","country":"Romania"},
{"cont_code":"EU","continent":"Europe","country_code":"RU","country_code3":"RUS","country_no":"643","country":"Russia"},
{"cont_code":"AF","continent":"Africa","country_code":"RW","country_code3":"RWA","country_no":"646","country":"Rwanda"},
{"cont_code":"AF","continent":"Africa","country_code":"SH","country_code3":"SHN","country_no":"654","country":"St. Helena"},
{"cont_code":"NA","continent":"North America","country_code":"KN","country_code3":"KNA","country_no":"659","country":"St. Kitts and Nevis"},
{"cont_code":"NA","continent":"North America","country_code":"LC","country_code3":"LCA","country_no":"662","country":"St. Lucia"},
{"cont_code":"NA","continent":"North America","country_code":"PM","country_code3":"SPM","country_no":"666","country":"St. Pierre and Miquelon"},
{"cont_code":"NA","continent":"North America","country_code":"VC","country_code3":"VCT","country_no":"670","country":"St. Vincent and the Grenadines"},
{"cont_code":"OC","continent":"Oceania","country_code":"WS","country_code3":"WSM","country_no":"882","country":"Samoa"},
{"cont_code":"EU","continent":"Europe","country_code":"SM","country_code3":"SMR","country_no":"674","country":"San Marino"},
{"cont_code":"AF","continent":"Africa","country_code":"ST","country_code3":"STP","country_no":"678","country":"Sao Tome and Principe"},
{"cont_code":"AS","continent":"Asia","country_code":"SA","country_code3":"SAU","country_no":"682","country":"Saudi Arabia"},
{"cont_code":"AF","continent":"Africa","country_code":"SN","country_code3":"SEN","country_no":"686","country":"Senegal"},
{"cont_code":"EU","continent":"Europe","country_code":"RS","country_code3":"SRB","country_no":"688","country":"Serbia"},
{"cont_code":"AF","continent":"Africa","country_code":"SC","country_code3":"SYC","country_no":"690","country":"Seychelles"},
{"cont_code":"AF","continent":"Africa","country_code":"SL","country_code3":"SLE","country_no":"694","country":"Sierra Leone"},
{"cont_code":"AS","continent":"Asia","country_code":"SG","country_code3":"SGP","country_no":"702","country":"Singapore"},
{"cont_code":"EU","continent":"Europe","country_code":"SK","country_code3":"SVK","country_no":"703","country":"Slovakia"},
{"cont_code":"EU","continent":"Europe","country_code":"SI","country_code3":"SVN","country_no":"705","country":"Slovenia"},
{"cont_code":"OC","continent":"Oceania","country_code":"SB","country_code3":"SLB","country_no":"90","country":"Solomon Islands"},
{"cont_code":"AF","continent":"Africa","country_code":"SO","country_code3":"SOM","country_no":"706","country":"Somalia"},
{"cont_code":"AF","continent":"Africa","country_code":"ZA","country_code3":"ZAF","country_no":"710","country":"South Africa"},
{"cont_code":"AN","continent":"Antarctica","country_code":"GS","country_code3":"SGS","country_no":"239","country":"South Georgia"},
{"cont_code":"EU","continent":"Europe","country_code":"ES","country_code3":"ESP","country_no":"724","country":"Spain"},
{"cont_code":"AS","continent":"Asia","country_code":"LK","country_code3":"LKA","country_no":"144","country":"Sri Lanka"},
{"cont_code":"AF","continent":"Africa","country_code":"SD","country_code3":"SDN","country_no":"736","country":"Sudan"},
{"cont_code":"SA","continent":"South America","country_code":"SR","country_code3":"SUR","country_no":"740","country":"Suriname"},
{"cont_code":"EU","continent":"Europe","country_code":"SJ","country_code3":"SJM","country_no":"744","country":"Svalbard"},
{"cont_code":"AF","continent":"Africa","country_code":"SZ","country_code3":"SWZ","country_no":"748","country":"Swaziland"},
{"cont_code":"EU","continent":"Europe","country_code":"SE","country_code3":"SWE","country_no":"752","country":"Sweden"},
{"cont_code":"EU","continent":"Europe","country_code":"CH","country_code3":"CHE","country_no":"756","country":"Switzerland"},
{"cont_code":"AS","continent":"Asia","country_code":"SY","country_code3":"SYR","country_no":"760","country":"Syria"},
{"cont_code":"AS","continent":"Asia","country_code":"TW","country_code3":"TWN","country_no":"158","country":"Taiwan"},
{"cont_code":"AS","continent":"Asia","country_code":"TJ","country_code3":"TJK","country_no":"762","country":"Tajikistan"},
{"cont_code":"AF","continent":"Africa","country_code":"TZ","country_code3":"TZA","country_no":"834","country":"Tanzania"},
{"cont_code":"AS","continent":"Asia","country_code":"TH","country_code3":"THA","country_no":"764","country":"Thailand"},
{"cont_code":"AS","continent":"Asia","country_code":"TL","country_code3":"TLS","country_no":"626","country":"Timor-Leste"},
{"cont_code":"AF","continent":"Africa","country_code":"TG","country_code3":"TGO","country_no":"768","country":"Togo"},
{"cont_code":"OC","continent":"Oceania","country_code":"TK","country_code3":"TKL","country_no":"772","country":"Tokelau"},
{"cont_code":"OC","continent":"Oceania","country_code":"TO","country_code3":"TON","country_no":"776","country":"Tonga"},
{"cont_code":"NA","continent":"North America","country_code":"TT","country_code3":"TTO","country_no":"780","country":"Trinidad and Tobago"},
{"cont_code":"AF","continent":"Africa","country_code":"TN","country_code3":"TUN","country_no":"788","country":"Tunisia"},
{"cont_code":"AS","continent":"Asia","country_code":"TR","country_code3":"TUR","country_no":"792","country":"Turkey"},
{"cont_code":"AS","continent":"Asia","country_code":"TM","country_code3":"TKM","country_no":"795","country":"Turkmenistan"},
{"cont_code":"NA","continent":"North America","country_code":"TC","country_code3":"TCA","country_no":"796","country":"Turks and Caicos Islands"},
{"cont_code":"OC","continent":"Oceania","country_code":"TV","country_code3":"TUV","country_no":"798","country":"Tuvalu"},
{"cont_code":"NA","continent":"North America","country_code":"VI","country_code3":"VIR","country_no":"850","country":"US Virgin Islands"},
{"cont_code":"AF","continent":"Africa","country_code":"UG","country_code3":"UGA","country_no":"800","country":"Uganda"},
{"cont_code":"EU","continent":"Europe","country_code":"UA","country_code3":"UKR","country_no":"804","country":"Ukraine"},
{"cont_code":"AS","continent":"Asia","country_code":"AE","country_code3":"ARE","country_no":"784","country":"United Arab Emirates"},
{"cont_code":"EU","continent":"Europe","country_code":"GB","country_code3":"GBR","country_no":"826","country":"UK"},
{"cont_code":"OC","continent":"Oceania","country_code":"UM","country_code3":"UMI","country_no":"581","country":"US Minor Outlying Islands"},
{"cont_code":"NA","continent":"North America","country_code":"US","country_code3":"USA","country_no":"840","country":"USA"},
{"cont_code":"SA","continent":"South America","country_code":"UY","country_code3":"URY","country_no":"858","country":"Uruguay"},
{"cont_code":"AS","continent":"Asia","country_code":"UZ","country_code3":"UZB","country_no":"860","country":"Uzbekistan"},
{"cont_code":"OC","continent":"Oceania","country_code":"VU","country_code3":"VUT","country_no":"548","country":"Vanuatu"},
{"cont_code":"SA","continent":"South America","country_code":"VE","country_code3":"VEN","country_no":"862","country":"Venezuela"},
{"cont_code":"AS","continent":"Asia","country_code":"VN","country_code3":"VNM","country_no":"704","country":"Vietnam"},
{"cont_code":"OC","continent":"Oceania","country_code":"WF","country_code3":"WLF","country_no":"876","country":"Wallis and Futuna Islands"},
{"cont_code":"AF","continent":"Africa","country_code":"EH","country_code3":"ESH","country_no":"732","country":"Western Sahara"},
{"cont_code":"AS","continent":"Asia","country_code":"YE","country_code3":"YEM","country_no":"887","country":"Yemen"},
{"cont_code":"AF","continent":"Africa","country_code":"ZM","country_code3":"ZMB","country_no":"894","country":"Zambia"},
{"cont_code":"AF","continent":"Africa","country_code":"ZW","country_code3":"ZWE","country_no":"716","country":"Zimbabwe"}
];
